# Generated by django-admin-grpc 0.3.0

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrpcAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_name", models.CharField(db_index=True, max_length=255)),
                ("operation", models.CharField(db_index=True, max_length=32)),
                ("pk_value", models.CharField(blank=True, db_index=True, max_length=255)),
                ("user", models.CharField(blank=True, db_index=True, max_length=255)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("diff", models.JSONField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("extra", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resource_name", "timestamp"], name="grpcaudit_resource_ts_idx"
                    ),
                    models.Index(fields=["user", "timestamp"], name="grpcaudit_user_ts_idx"),
                    models.Index(fields=["operation", "timestamp"], name="grpcaudit_op_ts_idx"),
                ],
            },
        ),
    ]
